content_app/urls.py
from django.urls import path, include
from .views import HomePage, ContactView, AboutPage, TouristPage
app_name = 'content_app'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutPage.as_view(), name='about'),
    path('tourist-spots/', TouristPage.as_view(), name='tourist-spots'),
]

hotel/urls.py
from django.urls import path
from .views import RoomListView, RoomDetailView, BookedRoomsView, CancelBookingView


app_name = 'hotel'
urlpatterns = [
    path('rooms/', RoomListView.as_view(), name = 'RoomListView'),
    path('rooms/<str:room_type>/', RoomDetailView.as_view(), name = 'RoomDetailView'),
    path('booked_rooms', BookedRoomsView.as_view(), name='BookedRoomsView'),
    path('booking/cancel/<int:pk>/', CancelBookingView.as_view(), name='CancelBookingView'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .admin import custom_admin

urlpatterns = [
    path('admin/', custom_admin.urls),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls')),
    path('hotel/', include("hotel.urls")),
    path('', include("content_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hotel.views.custom_404'

hotel/models.py
from django.db import models
from django.conf import settings

from .room_types import ROOM_TYPES

class RoomType(models.Model):
    room_type = models.CharField(max_length=15, choices=ROOM_TYPES, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.room_type


class RoomProperties(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    number_of_beds = models.IntegerField()
    capacity = models.IntegerField()
    price_per_night = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        verbose_name_plural = "Room properties"
    def __str__(self):
        return f"{self.room_type} room, {self.number_of_beds} bed(s), {self.capacity} person(s)"        

class Room(models.Model):
    room_number = models.IntegerField(unique=True)
    properties = models.ManyToManyField('RoomProperties')

class RoomImage(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='room_images/')

    def __str__(self):
        return self.room_type.room_type
    

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def get_room_type(self):
        room_types = dict(ROOM_TYPES)
        room_properties = self.room.properties.first() if self.room.properties.exists() else None
        if room_properties:
            return room_types.get(room_properties.room_type.room_type)
        else:
            return None

hotel/forms.py
from django import forms
from project_core.utils import DivErrorList

# create a form that accepts the check-in and check-out date from the user. this will be used to book a room
class BookingForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class':'form-control'})
    )
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class':'form-control'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_class = DivErrorList

hotel/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DeleteView
from django.http import Http404
from django.contrib import messages
from .room_types import ROOM_TYPES
from .models import Room, RoomType, Booking, RoomImage
from .forms import BookingForm
from hotel.utility_functions.room_availability import check_room_availability
from django.urls import reverse_lazy
from datetime import timezone, datetime

class RoomListView(ListView):
    model = RoomType
    context_object_name = 'rooms'
    template_name = "hotel/room_list.html"

     # create queryset based user's search input
    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('roomimage_set', 'roomproperties_set')

        #get search query from user input
        search_query = self.request.GET.get('search')

        if search_query:
            # filter queryset by the search key word and return closely matched results
            queryset = queryset.filter(
                Q(room_type__icontains=search_query)  # Match room type
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = self.request.GET.get('search')
        room_list = []
        for room_type in self.object_list:
            room_type_name = room_type.room_type
            room_url = reverse_lazy('hotel:RoomDetailView', kwargs={'room_type': room_type_name})
            room_list.append((room_type, room_url))
        context['room_list'] = room_list
        context['search'] = search_query
        return context

class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        # get the room type from the url
        room_type = self.kwargs.get('room_type', None)
        form = BookingForm()

        # get the list of rooms available in the room type
        room_list = Room.objects.filter(properties__room_type__room_type=room_type)

        # get the associated properties of the room type and return it
        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(ROOM_TYPES).get(room.properties.all().first().room_type.room_type, None)
            room_type_obj = RoomType.objects.get(room_type=room_type)  # Get RoomType object
            room_images = RoomImage.objects.filter(room_type=room_type_obj)

            context = {
                'room_category': room_category,
                'form': form,
                'room_images':room_images,
                'room_type_obj':room_type_obj,
            }
            return render(request, 'hotel/room_detail_view.html', context)
        else:
            # return a 404 message if there are no rooms in that category
            raise Http404('Category does not exist')
    
    # Post request to handle the event where the user decides to book a room
    def post(self, request, *args, **kwargs):
        # get the room type from the url
        room_type = self.kwargs.get('room_type', None)

        # get all the rooms for that specific room type
        room_list = Room.objects.filter(properties__room_type__room_type=room_type)

        form = BookingForm(request.POST)


        if form.is_valid():
            # get data from the form
            data = form.cleaned_data

            check_out = data['check_out'].replace(tzinfo=timezone.utc)
            current_day = datetime.now(timezone.utc)

            # validate if user is booking the room with correct dates and time
            if check_out < data['check_in'] or data['check_in'] < current_day:
                form.add_error('check_out', 'Cannot check out earlier than the check-in time')
                form.add_error('check_in', 'Cannot check in at a previous date')
                return render(request, 'hotel/room_detail_view.html', {'form': form})


        # check for the number of rooms available in the room type the user chooses at the specified time
        available_rooms = []
        for room in room_list:
            if check_room_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)
        
        # book the first available room for the user
        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            messages.success(request, f'You have successfully booked a {room_type} room')
            return redirect('hotel:BookedRoomsView')
        # return an error message if there is no available room in the chosen room type at that period
        else:
            messages.error(request, f'All {room_type} rooms have been booked at this period. Please try another one or book at a different time.')
            return redirect('hotel:RoomListView')


# views for rooms booked by a user
class BookedRoomsView(ListView):
    model = Booking
    template_name = 'hotel/booked_rooms.html'

    def get_queryset(self):
        # return all the booked rooms if the current user is an admin, otherwise, return only the room booked by the current user
        if self.request.user.is_staff:
            return Booking.objects.all()
        else:
            return Booking.objects.filter(user=self.request.user)
        
    # override the default context for class-based views to return booked rooms
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        booked_rooms = self.get_queryset()
        room_prices = []
        room_images = []
        room_descriptions = []
        booking_status=[]
        current_date = datetime.now(timezone.utc)
        
        for booked_room in booked_rooms:
            room_properties = booked_room.room.properties.first()
            if room_properties:
                room_prices.append(room_properties.price_per_night)
                room_image = RoomImage.objects.filter(room_type=room_properties.room_type).first()
                if room_image:
                    room_images.append(room_image.image.url)
                else:
                    room_images.append(None)

                # get the room description of each room type
                room_descriptions.append(room_properties.room_type.description)

                # check if user is trying to checking out at a previous date 
                booking_status.append(booked_room.check_out >= current_date)
            else:
                room_prices.append(None)
                room_images.append(None)
                room_descriptions.append(None)
                booking_status.append(False)

        # return the booked rooms and their properties
        context['booked_rooms'] = zip(booked_rooms, room_prices, room_images, room_descriptions, booking_status)
        return context

# View for users to cancel their hotel bookings
class CancelBookingView(DeleteView):
    model = Booking
    success_url = reverse_lazy('hotel:BookedRoomsView')


# custom 404 error page view
def custom_404(request, exception):
    return render(request, '404.html', status=404)

hotel/templates/hotel/booked_rooms.html
{% extends 'base.html' %}
{% load static humanize%}

{% block title %} Booked rooms {% endblock title %}
{% block content %}
        {% comment %} <!-- Page Header Start--> {% endcomment %}
        {% include 'flash_messages.html' %}
        <div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-1.jpg' %}');">
            <div class="container-fluid page-header-inner py-5">
                <div class="container text-center pb-5">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Booked Rooms</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{%url 'hotel:RoomListView'%}">Rooms</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Booked Rooms</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        {% comment %} <!-- Page Header End --> {% endcomment %}

{% comment %} <!-- Booked Rooms Start --> {% endcomment %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-accent text-uppercase">Booked Rooms</h6>
            <h1 class="mb-5">View {% if user.is_authenticated %}All {% else %} Your {% endif %} Booked <span class="text-accent text-uppercase">Rooms</span></h1>
        </div>
        <a href="{% url 'hotel:RoomListView' %}" class="btn btn-dark my-3" role="button">Book a Room</a>
        <div class="row g-4">

            {% comment %} <!--list all the rooms booked by the user--> {% endcomment %}
            {% for booked_room, price, image, description, checked_in in booked_rooms %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="room-item shadow rounded overflow-hidden">
                    <div class="position-relative">
                        <img class="img-fluid" src="{{ image }}" alt="{{ booked_room.room_type }}" style="height:250px; width: 100%;">
                        <small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">{{price|intcomma}} NGN/Night</small>
                    </div>
                    <div class="p-4 mt-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h5 class="mb-0">{{booked_room.get_room_type|capfirst}} </h5>
                        </div>
                        <div class="d-flex mb-3">
                            <small class="border-end me-3 pe-3"><i class="fa fa-bed text-accent me-2"></i>Beds: {{ booked_room.room.properties.first.number_of_beds }}</small>
                            <small class="border-end me-3 pe-3"><i class="fas fa-users text-accent me-2"></i>Capacity: {{ booked_room.room.properties.first.capacity }}</small>
                        </div>
                        <strong><small class="d-block">Check in: {{booked_room.check_in}}</small></strong>
                        <strong><small class="d-block">Check out: {{booked_room.check_out}}</small></strong>
                        <p class="text-body mb-3 mt-2">{{ description|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between">

                            {% comment %} <!--prevent user from canclling a booked room if they have already checked out--> {% endcomment %}
                            {% if not checked_in %}
                            <button type="button" class="btn btn-secondary" disabled>Checked out</button>
                            {% else %}
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelbookingModal{{ booked_room.pk }}">
                                Cancel Booking
                            </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            
        {% comment %} <!-- Modal start --> {% endcomment %}
            <div class="modal fade" id="cancelbookingModal{{ booked_room.pk }}" tabindex="-1" aria-labelledby="cancelbookingModalLabel{{ booked_room.pk }}" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="cancelbookingModalLabel{{ booked_room.pk }}">Cancel Booking</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <h4>Are you sure you want to cancel this booking?</h4>
                        </div>
                        <div class="modal-footer">
                            <form method="post" action="{% url 'hotel:CancelBookingView' booked_room.pk %}">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" value="Yes">
                            </form>
                            <button class="btn btn-primary mx-4" data-bs-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
        {% comment %} <!-- Modal end --> {% endcomment %}
             
            {% empty %}
            {% comment %} <!-- return an error message if the user does not have a booked room --> {% endcomment %}
            <div class="col">
                <center>
                    <div class="container">
                        <h1>Oops!</h1>
                        <h4>You currently do not have any booked rooms. Click the button below to book a room.</h4>
                        <a class="btn btn-primary" href="{% url 'hotel:RoomListView' %}">Book a Room</a>
                    </div>
                </center>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% comment %} <!-- Booked Rooms End --> {% endcomment %}

{% endblock content %}

hotel/templates/hotel/room_detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Book a {{room_category}} {% endblock title %}
{% block content %}
{% comment %} <!-- Page Header Start --> {% endcomment %}
<div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-1.jpg' %}');">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Our {{room_category}}s</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{%url 'hotel:RoomListView'%}">Rooms</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">{{room_category}}</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
{% comment %} <!-- Page Header End --> {% endcomment %}
<div class="container">
    <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
        <h6 class="section-title text-center text-accent text-uppercase">Our Rooms</h6>
        <h1 class="mb-5">Explore Our <span class="text-accent text-uppercase">Rooms</span></h1>
    </div>
    <div class="row my-5">
        {% comment %} <!-- Create a carousel with the images available for the rooms --> {% endcomment %}
        <div class="col-md-6 wow fadeInUp" data-wow-delay="0.1s"> 
            <div id="carouselExampleIndicators" class="carousel slide" style="overflow: hidden; width: auto;">

                {% comment %} <!--Use the room images as carousel indicators --> {% endcomment %}
                <div class="carousel-indicators">
                {% for image in room_images %}
                    <img src="{{ image.image.url }}" style="height: 35px; width: 35px;" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}"></img>
                {% endfor %}
                </div>

                <div class="carousel-inner">
                {% for image in room_images %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img src="{{ image.image.url }}" class="d-block w-100 img-fluid" alt="Slide {{ forloop.counter }}">
                    </div>
                {% endfor %}
                </div>
                <button class="carousel-control-prev " type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon btn-primary" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon btn-primary" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>

        <div class="col-md-6 wow fadeInUp" data-wow-delay="0.5s">
            <div class="room-description" style="white-space: pre-wrap; ">
                <p>{{room_type_obj.description}}</p>
            </div>
        </div>
    </div>

    <div class="book-rooom">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-accent text-uppercase">Rooms</h6>
            <h1 class="mb-5">Book a <span class="text-accent">{{room_category}}</span></h1>
        </div>
        {% comment %} <!--prevent guest users from bookinig a room by asking them to log in first --> {% endcomment %}
        {% if not user.is_authenticated %}
        <h3 class="text-center mb-4">Please <a href="{% url 'account_login' %}" class="text-accent">log in</a> to book a room</h3>
        {% endif %}
        <div class="row">
            <div class="col-md-6 my-3">
                <img src="{% static 'img/signup.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6 d-flex align-items-center">
                <form method="post" class="wow fadeInUp" data-wow-delay="0.1s">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="{{form.check_in.id_for_label}}">Check in</label> <br>
                                {{ form.check_in }}
                                {{ form.check_in.errors|safe }}
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="{{form.check_out.id_for_label}}">Check out</label> <br>
                                {{ form.check_out }}
                                {{ form.check_out.errors|safe }}
                            </div>
                        </div>
                    </div>
                    {% comment %} <!--disable button to prevent guest users from booking a room --> {% endcomment %}
                        <input class="btn btn-primary py-2 my-3 bg-accent" type="submit" value="Book room" {% if not user.is_authenticated %} disabled {% endif %}>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

hotel/templates/hotel/room_list.html
{% extends 'base.html'  %}
{% load static %}

{% block title %} Our rooms {% endblock title %}
{% block content %}
        {% comment %} <!-- Page Header Start --> {% endcomment %}
        {% include 'flash_messages.html' %}
        <div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-1.jpg' %}');">
            <div class="container-fluid page-header-inner py-5">
                <div class="container text-center pb-5">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Rooms</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Rooms</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        {% comment %} <!-- Page Header End --> {% endcomment %}

<div class="container">
    <div class="row justify-content-end">
        <div class="col-md-4">
            <form method="GET" action="{% url 'hotel:RoomListView' %}">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" required placeholder="Search for a room">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>        
{% comment %} <!--check if the user searches for a room--> {% endcomment %}
{% if request.GET.search %}
        {% comment %} <!-- return search result based on user's search keyword --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
            {% if rooms %}
                <h1>You searched for {{search}}</h1> 
                <div class="row g-4">
                    {% for room, room_url in room_list %}
                    {% include 'rooms_list.html' %}
                    {% endfor %}
                </div>
             {% else %}
             {% comment %} <!--return error message if user's search query does not  match any rooms--> {% endcomment %}
             <center>
                 <div class="container">
                     <h1 class="emoji">😕</h1>
                     <h1>Oops!</h1>
                     <h4>We currently do not have the room you searched for. Please search for another room.</h4>
                     <a class="btn btn-primary" href="{% url 'hotel:RoomListView' %}">View all rooms</a>
                 </div>
             </center>
             {% endif %}
            </div>
        </div>
{% else %}
        {% comment %} <!-- Room start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-accent text-uppercase">Our Rooms</h6>
                    <h1 class="mb-5">Explore Our <span class="text-accent text-uppercase">Rooms</span></h1>
                </div>
                <div class="row g-4">
                    {% for room, room_url in room_list %}
                    {% include 'rooms_list.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% comment %} <!-- Room end --> {% endcomment %}
{% endif %}
{% endblock content %}