content_app/urls.py
from django.urls import path, include
from .views import HomePage, ContactView, AboutPage, TouristPage
app_name = 'content_app'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutPage.as_view(), name='about'),
    path('tourist-spots/', TouristPage.as_view(), name='tourist-spots'),
]

hotel/urls.py
from django.urls import path
from .views import RoomListView, RoomDetailView, BookedRoomsView, CancelBookingView


app_name = 'hotel'
urlpatterns = [
    path('rooms/', RoomListView.as_view(), name = 'RoomListView'),
    path('rooms/<str:room_type>/', RoomDetailView.as_view(), name = 'RoomDetailView'),
    path('booked_rooms', BookedRoomsView.as_view(), name='BookedRoomsView'),
    path('booking/cancel/<int:pk>/', CancelBookingView.as_view(), name='CancelBookingView'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .admin import custom_admin

urlpatterns = [
    path('admin/', custom_admin.urls),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls')),
    path('hotel/', include("hotel.urls")),
    path('', include("content_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hotel.views.custom_404'

content_app/models.py
from django.db import models

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "User Feedback"
        verbose_name_plural = "User Feedback"
    
    def __str__(self):
        return self.subject

class TouristSpot(models.Model):
    tourist_spot_name= models.CharField(max_length=400)
    image = models.ImageField(upload_to='tourist_spots/')
    description = models.TextField()
    link = models.URLField()

    def __str__(self):
        return self.tourist_spot_name

hotel/models.py
from django.db import models
from django.conf import settings

from .room_types import ROOM_TYPES

class RoomType(models.Model):
    room_type = models.CharField(max_length=15, choices=ROOM_TYPES, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.room_type


class RoomProperties(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    number_of_beds = models.IntegerField()
    capacity = models.IntegerField()
    price_per_night = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        verbose_name_plural = "Room properties"
    def __str__(self):
        return f"{self.room_type} room, {self.number_of_beds} bed(s), {self.capacity} person(s)"        

class Room(models.Model):
    room_number = models.IntegerField(unique=True)
    properties = models.ManyToManyField('RoomProperties')

class RoomImage(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='room_images/')

    def __str__(self):
        return self.room_type.room_type
    

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def get_room_type(self):
        room_types = dict(ROOM_TYPES)
        room_properties = self.room.properties.first() if self.room.properties.exists() else None
        if room_properties:
            return room_types.get(room_properties.room_type.room_type)
        else:
            return None

content_app/forms.py
from django import forms
from .models import ContactMessage
from project_core.utils import DivErrorList

# a form to take in user feedback from the contact page
class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Your Message', 'rows': 5}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_class = DivErrorList

content_app/views.py
from django.shortcuts import render
from hotel.views import RoomListView
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, ListView
from django.urls import reverse_lazy
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.template.loader import render_to_string
from .forms import ContactForm
from .models import TouristSpot

# this view from the homepage inherits from the hotel.RoomListView view in the hotel app
class HomePage(RoomListView):
    template_name = 'content_app/index.html'

class AboutPage(TemplateView):
    template_name = 'content_app/about.html'

class TouristPage(ListView):
    template_name = 'content_app/tourist.html'
    context_object_name = 'tourist_places'
    model = TouristSpot

# contact view for user to send feedback and make enquires
class ContactView(FormView):
    template_name = 'content_app/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('content_app:contact')

    # if the form is valid, save the message to the model, send an email to the user and an admin email specified.
    def form_valid(self, form):
        # Save the message in the database
        form.save()

        # Send the email
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']

        # Prepare the email data
        email_data = {
            'name': name,
            'email': email,
            'subject': subject,
            'message': message,
        }

        # Send the email to the specified destination email
        send_mail(
            f'New Contact Message - {subject}',
            '',
            settings.DEFAULT_FROM_EMAIL,
            [settings.CONTACT_EMAIL],
            html_message=render_to_string('contact_mail/contact_message.html', email_data),
        )

        # Send email to the user
        user_email_data = {
            'name': name,
            'email': email,
        }

        send_mail(
            'Thank you for contacting us',
            '',
            settings.DEFAULT_FROM_EMAIL,
            [email],
            html_message=render_to_string('contact_mail/contact_user.html', user_email_data),
        )

        messages.success(self.request, 'Your message has been sent successfully!')

        return super().form_valid(form)

content_app/templates/content_app/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Hotel Miramar SG | About us {% endblock title %}
{% block content %}
    {% comment %} <!-- Page Header Start --> {% endcomment %}
    {% include 'flash_messages.html' %}
    <div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-1.jpg' %}');">
        <div class="container-fluid page-header-inner py-5">
            <div class="container text-center pb-5">
                <h1 class="display-3 text-white mb-3 animated slideInDown">About</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center text-uppercase">
                        <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">About</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    {% comment %} <!-- Page Header End --> {% endcomment %}

    <div class="container">
        <div class="row">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title text-center text-accent text-uppercase">Our Vision</h6>
                <h1 class="mb-5"><span class="text-accent">Unveiling</span> Tomorrow's Possibilities</h1>
            </div>
            <div class="col-md-6">
                <img src="{% static 'img/about-vision.jpg' %}" alt="" class="img-fluid wow fadeInUp" data-wow-delay="0.1s">
            </div>
            <div class="col-md-6 d-flex align-items-center my-3 wow fadeInUp" data-wow-delay="0.5s">
                <div>
                    <p>
                        Our vision at Hotel Miramar SG is to redefine the hospitality industry by creating unforgettable experiences for our guests. We strive to go beyond the ordinary and set new standards of excellence. With a commitment to innovation and personalized service, we aim to unveil tomorrow's possibilities in the world of hospitality.
                    </p>
                    <p>
                        At Hotel Miramar SG, we believe that every guest deserves a unique and exceptional stay. Our dedicated team of professionals is passionate about creating a welcoming and comfortable environment, where guests can relax and indulge in luxury. From our thoughtfully designed rooms to our world-class amenities, we aim to exceed expectations and provide a truly memorable experience. Whether you are traveling for business or leisure, we are dedicated to making your stay with us an unforgettable one.
                    </p>
                </div>
            </div>
        </div>
        
        <div class="row my-5">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title text-center text-accent text-uppercase">Our Mission</h6>
                <h1 class="mb-5"><span class="text-accent">Unleashing</span> Hospitality's Future</h1>
            </div>
            <div class="col-md-6 d-flex align-items-center my-3 wow fadeInUp" data-wow-delay="0.1s">
                <div>
                    <p>
                        At Hotel Miramar SG, our mission is to redefine the hospitality landscape by delivering unparalleled experiences to our guests. We strive to create a harmonious blend of luxury, comfort, and personalized service that exceeds expectations. Our dedicated team is committed to unleashing the future of hospitality, where every moment is crafted with utmost care and attention to detail.
                    </p>
                    <p>
                        With a relentless pursuit of excellence, we aim to create a haven of tranquility and indulgence for our guests. From the moment you step into our elegant lobby, you will be greeted with warm smiles and a genuine desire to make your stay exceptional. Whether you are here for business or leisure, our mission is to provide a seamless and memorable experience that leaves a lasting impression.
                    </p>
                    <p>
                        At Hotel Miramar SG, we believe that true hospitality goes beyond providing a place to stay. It is about creating moments of joy, surprise, and delight. From our thoughtfully designed rooms and world-class amenities to our exceptional dining options and rejuvenating spa, every aspect of your stay is carefully curated to ensure your utmost satisfaction. Join us on this journey as we unleash the future of hospitality and create unforgettable memories together.
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static 'img/about-mission.jpg' %}" alt="" class="img-fluid wow fadeInUp" data-wow-delay="0.5s">
            </div>
        </div>
    </div>
{% endblock content %}

content_app/templates/content_app/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contact us {% endblock title %}

{% block content %}
        {% comment %} <!-- Page Header Start --> {% endcomment %}
        {% include 'flash_messages.html' %}
        <div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-1.jpg' %}');">
            <div class="container-fluid page-header-inner py-5">
                <div class="container text-center pb-5">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Contact</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Contact</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        {% comment %} <!-- Page Header End --> {% endcomment %}


        {% comment %} <!-- Contact start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-accent text-uppercase">Contact Us</h6>
                    <h1 class="mb-5">Send Your<span class="text-accent text-capitalize"> feedback</span> or Query</h1>
                </div>
                <div class="row g-4">
                    <div class="col-12">
                        <div class="row gy-4">
                            <div class="col-md-4">
                                <h6 class="section-title text-start text-accent text-uppercase">Booking</h6>
                                <p><i class="fa fa-envelope-open text-accent me-2"></i>book@hotelmiramarsg.org</p>
                            </div>
                            <div class="col-md-4">
                                <h6 class="section-title text-start text-accent text-uppercase">General</h6>
                                <p><i class="fa fa-envelope-open text-accent me-2"></i>info@hotelmiramarsg.org</p>
                            </div>
                            <div class="col-md-4">
                                <h6 class="section-title text-start text-accent text-uppercase">Technical</h6>
                                <p><i class="fa fa-envelope-open text-accent me-2"></i>tech@hotelmiramarsg.org</p>
                            </div>
                        </div>
                    </div>
                    {% comment %} <!-- Hotel Location on map --> {% endcomment %}
                    <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
                            <iframe class="position-relative rounded w-100 h-100" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d507401.6273486709!2d3.445211782022276!3d6.512164132981826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf75df5c74367%3A0x6a7e7df9d6c1cd4a!2sLekki%2C%20Lagos!5e0!3m2!1sen!2sng!4v1689464495235!5m2!1sen!2sng" style="min-height: 350px; border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" aria-hidden="false"tabindex="0" frameborder="0"></iframe>
                    </div>
                    <div class="col-md-6">
                        <div class="wow fadeInUp" data-wow-delay="0.2s">
                            {% comment %} <!-- Contact form start --> {% endcomment %}
                            <form method="post">
                                {{ form.non_field_errors | safe }}
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating form-group">
                                            {{ form.name }}
                                            <label for="{{ form.name.id_for_label }}">Your Name</label>
                                            {{ form.name.errors|safe }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating form-group">
                                            {{ form.email }}
                                            <label for="{{ form.email.id_for_label }}">Your Email</label>
                                            {{ form.email.errors|safe }}
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating form-group">
                                            {{ form.subject }}
                                            <label for="form.subject.id_for_label">Subject</label>
                                            {{ form.subject.errors|safe }}
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating form-group">
                                            {{ form.message }}
                                            <label for="form.message.id_for_label">Message</label>
                                            {{ form.message.errors|safe }}
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                                    </div>
                                </div>
                            </form>
                            {% comment %} <!-- Contact form End --> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <!-- Contact End --> {% endcomment %}
{% endblock content %}

content_app/templates/content_app/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Welcome to Hotel Miramar SG {% endblock title %}
{% block content %}
{% comment %} <!-- About Start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6">
                        <h6 class="section-title text-start text-accent text-uppercase">About Us</h6>
                        <h1 class="mb-4">Welcome to <span class="text-accent text-uppercase">Hotel Miramar SG</span></h1>
                        <p class="mb-4">Here, every moment is designed to make your stay truly memorable. Discover the allure of Hotel Miramar SG. Immerse yourself in our luxury oasis in the heart of Singapore. Whether you're here for business or leisure, our elegant rooms, delectable dining, and top-notch service await. Indulge in breathtaking views, explore nearby attractions, and experience the perfect blend of comfort and sophistication.</p>
                        <a class="btn btn-primary py-3 px-5 mt-2" href="{% url 'content_app:about' %}">Explore More</a>
                    </div>
                    <div class="col-lg-6">
                        <div class="row g-3">
                            <div class="col-6 text-end">
                                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.1s" src="{% static 'img/about-1.jpg' %}" style="margin-top: 25%;">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.3s" src="{% static 'img/about-2.jpg' %}">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid rounded w-50 wow zoomIn" data-wow-delay="0.5s" src="{% static 'img/about-3.jpg' %}">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.7s" src="{% static 'img/about-4.jpg' %}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <!-- About End --> {% endcomment %}
        
        {% comment %} <!-- Room start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-accent text-uppercase">Our Rooms</h6>
                    <h1 class="mb-5">Explore Our <span class="text-accent text-uppercase">Rooms</span></h1>
                </div>
                <div class="row g-4">
                    {% comment %} <!--List only the first 3 rooms on the home page --> {% endcomment %}
                    {% for room, room_url in room_list|slice:":3" %}
                    {% include 'rooms_list.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% comment %} <!-- Room End --> {% endcomment %}

        {% comment %} <!-- Hotel services start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-accent text-uppercase">Our Services</h6>
                    <h1 class="mb-5">Explore Our <span class="text-accent text-uppercase">Services</span></h1>
                </div>
                <div class="row g-4">
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-bed fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">Accomodation</h5>
                            <p class="text-body mb-0">Unwind in our plush rooms and suites, a haven of comfort and style.</p>
                        </a>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-utensils fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">Dining Facilities</h5>
                            <p class="text-body mb-0">Savor culinary delights in our diverse restaurants and cafes, catering to every taste.</p>
                        </a>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-broom fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">House keeping</h5>
                            <p class="text-body mb-0">Impeccable cleanliness and attentive service ensure a pristine retreat.</p>
                        </a>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-concierge-bell fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">Concierge Services</h5>
                            <p class="text-body mb-0">Elevate your stay with personalized assistance from our knowledgeable team.</p>
                        </a>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-wifi fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">Wi-Fi and Connectivity</h5>
                            <p class="text-body mb-0">Stay connected with reliable high-speed internet throughout your visit</p>
                        </a>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                        <a class="service-item rounded" href="">
                            <div class="service-icon bg-transparent border rounded p-1">
                                <div class="w-100 h-100 border rounded d-flex align-items-center justify-content-center">
                                    <i class="fa fa-dumbbell fa-2x text-accent"></i>
                                </div>
                            </div>
                            <h5 class="mb-3 service-text">GYM & Yoga</h5>
                            <p class="text-body mb-0">Maintain your fitness routine with our modern gym and revitalizing yoga sessions.</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <!-- Hotel services End --> {% endcomment %}


        {% comment %} <!-- Image before footer start --> {% endcomment %}
        <div class="container-xxl before-footer my-5 py-5 bg-dark wow zoomIn" style="height: 40vh;" data-wow-delay="0.1s"></div>
        {% comment %} <!-- Image before footer End --> {% endcomment %}
{% endblock content %}

content_app/templates/content_app/tourist.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 

{% comment %} <!-- Page Header Start --> {% endcomment %}
<div class="container-fluid page-header mb-5 p-0" style="background-image: url('{% static 'img/about-2.jpg' %}');">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Tourist Spots</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{%url 'content_app:home'%}">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Tourist Spots</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
{% comment %} <!-- Page Header End --> {% endcomment %}

<div class="container-xxl py-5">
    <div class="container">
        {% comment %} <!-- Room start --> {% endcomment %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title text-center text-accent text-uppercase">Tourist Spots</h6>
                    <h1 class="mb-5">Explore The <span class="text-accent text-capitalize"> tourist spots</span> Around Us</h1>
                </div>
                <div class="row g-4">
                    
                    {% comment %} <!--List the nearby tourist spots --> {% endcomment %}
                    {% for place in tourist_places %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="room-item shadow rounded overflow-hidden">
                            <div class="position-relative">
                                <img class="img-fluid" src="{{ place.image.url }}" alt="{{ room.room_type }}" style="height: 250px; width: 100%;">
                            </div>
                            <div class="p-4 mt-2">
                                <div class="d-flex justify-content-between mb-3">
                                    <h5 class="mb-0">{{ place.tourist_spot_name|capfirst|truncatechars:25 }}</h5>
                                </div>
                                <p class="text-body mb-3" style="white-space: pre-wrap;"> {{ place.description|truncatechars:300 }}</p>
                                <div class="d-flex justify-content-between">
                                    <a class="btn btn-sm btn-primary rounded py-2 px-4" target="_blank" href="{{ place.link }}">Visit </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% empty %}
                    <h2 class="text-center">Sorry, there are no tourist spots around us right now.😔</h2>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% comment %} <!-- Room End --> {% endcomment %}
    </div>
</div>

{% endblock content %}