hotel/urls.py
from django.urls import path
from .views import RoomListView, RoomDetailView, BookedRoomsView, CancelBookingView


app_name = 'hotel'
urlpatterns = [
    path('rooms/', RoomListView.as_view(), name = 'RoomListView'),
    path('rooms/<str:room_type>/', RoomDetailView.as_view(), name = 'RoomDetailView'),
    path('booked_rooms', BookedRoomsView.as_view(), name='BookedRoomsView'),
    path('booking/cancel/<int:pk>/', CancelBookingView.as_view(), name='CancelBookingView'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .admin import custom_admin

urlpatterns = [
    path('admin/', custom_admin.urls),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls')),
    path('hotel/', include("hotel.urls")),
    path('', include("content_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hotel.views.custom_404'

users/urls.py
from django.urls import path
from .views import ProfileView, UpdateProfileView
app_name = 'users'
urlpatterns = [
    path('', ProfileView.as_view(), name='ProfileView'),
    path('update/', UpdateProfileView.as_view(), name='UpdateProfileView'),
]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.exceptions import ValidationError
from django.db import models

# a customer user manager to create normal and super users
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email field must be set')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


# a simple form to check the image size uploaded by the user
def validate_image_size(image):
    max_upload_size = 2 * 1024 * 1024  # 2MB

    # prevent users from uploading images larger than 2mb
    if image.size > max_upload_size:
        raise ValidationError("The uploaded image size is too large. Please upload an image smaller than 2MB.")

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = None 
    profile_picture = models.ImageField(
        upload_to='profile_pictures',
        default='default.png',
        blank=True,
        null=True,
        validators=[validate_image_size]
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

users/forms.py
from django import forms
from .models import User
from allauth.account.forms import SignupForm, LoginForm
from project_core.utils import DivErrorList

# form for the user to update their profile
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'profile_picture']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'profile_picture': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


# create a custom signup for that overrides the default form by django all auth
class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': 'First Name', 'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Last Name', 'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Email', 'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Password', 'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password', 'class': 'form-control'})
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.error_class = DivErrorList

    # save the custom login form with the new fields 
    def save(self, request):
        user = super().save(request)
        if user:
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()
        return user

# create a custom login for that overrides the default form by django all auth
class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        # add a custom css class to the fields
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({'placeholder': 'Email', 'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Password', 'class': 'form-control'})
        self.fields['remember'].widget.attrs.update({ 'class': 'form-check-input'})
        self.error_class = DivErrorList

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView
from .forms import UserProfileForm
from .models import User

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/update_profile.html'
    success_url = reverse_lazy('users:ProfileView')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/profile.html
{% extends 'base.html' %}


{% block title %} {{user.first_name}} {{user.last_name}} profile {% endblock title %}
{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-md-4">
            {% if user.profile_picture %}
                <img src="{{ user.profile_picture.url }}" alt="Profile Picture" class="img-fluid">
            {% else %}
                <img src="/media/default.png" alt="Default Profile Picture" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-md-8 my-3">
          <h1>{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</h1>
          <form>
            <div class="form-group my-3">
              <label for="firstName" class="text-accent"><b>First Name</b></label>
              <input type="text" class="form-control" id="firstName" value="{{ user.first_name }}" readonly>
            </div>
            <div class="form-group my-3">
              <label for="lastName" class="text-accent"><b>Last Name</b></label>
              <input type="text" class="form-control" id="lastName" value="{{ user.last_name }}" readonly>
            </div>
            <div class="form-group my-3">
              <label for="email" class="text-accent"><b>Email</b></label>
              <input type="email" class="form-control" id="email" value="{{ user.email }}" readonly>
            </div>
            <a href="{% url 'users:UpdateProfileView' %}" class="btn btn-dark my-3"><b>Update Profile</b></a>
          </form>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/update_profile.html
{% extends 'base.html' %}
{% block title %} Update your profile {% endblock title %}
{% block content %}
    <h1 class="text-center my-3">Update Profile</h1>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {{ form.non_field_errors | safe }}
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group my-2">
                        <label for="{{form.first_name.id_for_label}}" class="text-accent"><b>First Name</b></label>
                        {{ form.first_name }}
                        {{ form.first_name.errors|safe }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group my-2">
                        <label for="{{form.last_name.id_for_label}}" class="text-accent"><b>Last Name</b></label>
                        {{ form.last_name }}
                        {{ form.last_name.errors|safe }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group my-2">
                        <label for="{{form.email.id_for_label}}" class="text-accent"><b>Email</b></label>
                        {{ form.email }}
                        {{ form.email.errors|safe }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group my-2">
                        <label for="{{form.profile_picture.id_for_label}}" class="text-accent"><b>Profile Picture</b></label>
                        {{ form.profile_picture }}
                        {{ form.profile_picture.errors|safe }}
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-dark my-3">Update</button>
        </form>
    </div>
{% endblock %}