content_app/urls.py
from django.urls import path, include
from .views import HomePage, ContactView, AboutPage, TouristPage
app_name = 'content_app'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutPage.as_view(), name='about'),
    path('tourist-spots/', TouristPage.as_view(), name='tourist-spots'),
]

hotel/urls.py
from django.urls import path
from .views import RoomListView, RoomDetailView, BookedRoomsView, CancelBookingView


app_name = 'hotel'
urlpatterns = [
    path('rooms/', RoomListView.as_view(), name = 'RoomListView'),
    path('rooms/<str:room_type>/', RoomDetailView.as_view(), name = 'RoomDetailView'),
    path('booked_rooms', BookedRoomsView.as_view(), name='BookedRoomsView'),
    path('booking/cancel/<int:pk>/', CancelBookingView.as_view(), name='CancelBookingView'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .admin import custom_admin

urlpatterns = [
    path('admin/', custom_admin.urls),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls')),
    path('hotel/', include("hotel.urls")),
    path('', include("content_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hotel.views.custom_404'

users/urls.py
from django.urls import path
from .views import ProfileView, UpdateProfileView
app_name = 'users'
urlpatterns = [
    path('', ProfileView.as_view(), name='ProfileView'),
    path('update/', UpdateProfileView.as_view(), name='UpdateProfileView'),
]

hotel/models.py
from django.db import models
from django.conf import settings

from .room_types import ROOM_TYPES

class RoomType(models.Model):
    room_type = models.CharField(max_length=15, choices=ROOM_TYPES, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.room_type


class RoomProperties(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    number_of_beds = models.IntegerField()
    capacity = models.IntegerField()
    price_per_night = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        verbose_name_plural = "Room properties"
    def __str__(self):
        return f"{self.room_type} room, {self.number_of_beds} bed(s), {self.capacity} person(s)"        

class Room(models.Model):
    room_number = models.IntegerField(unique=True)
    properties = models.ManyToManyField('RoomProperties')

class RoomImage(models.Model):
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='room_images/')

    def __str__(self):
        return self.room_type.room_type
    

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def get_room_type(self):
        room_types = dict(ROOM_TYPES)
        room_properties = self.room.properties.first() if self.room.properties.exists() else None
        if room_properties:
            return room_types.get(room_properties.room_type.room_type)
        else:
            return None

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">  

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- libraries Stylesheet -->
    <link href="{% static 'libraries/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'libraries/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'libraries/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <title>{% block title %}{{ block.super|default:"Hotel Miramar SG" }}{% endblock title %}</title>
</head>
<body>
    <main class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-accent" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Header Start -->
        <header class="container-fluid bg-dark px-0">
            <div class="row gx-0">
                <div class="col-lg-3 bg-dark d-none d-lg-block">
                    <a href="{% url 'content_app:home' %}" class="navbar-brand w-100 h-100 m-0 p-0 d-flex align-items-center justify-content-center">
                        <h3 class="m-0 text-accent text-uppercase">Hotel Miramar SG</h3>
                    </a>
                </div>
                <div class="col-lg-9">
                    <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3 p-lg-0">
                        <a href="/" class="navbar-brand d-block d-lg-none">
                            <h3 class="m-0 text-accent text-uppercase">Hotel Miramar SG</h3>
                        </a>
                        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                            <div class="navbar-nav mr-auto py-0">
                                <a href="{% url 'content_app:home' %}" class="nav-item nav-link text-white">Home</a>
                                <a href="{% url 'content_app:about' %}" class="nav-item nav-link text-white">About</a>
                                <a href="{% url 'hotel:RoomListView' %}" class="nav-item nav-link text-white">Rooms</a>
                                <a href="{% url 'content_app:contact' %}" class="nav-item nav-link text-white">Contact</a>
                                <a href="{% url 'content_app:tourist-spots' %}" class="nav-item nav-link text-white">Tourist Spots</a>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'hotel:BookedRoomsView' %}" class="nav-item nav-link text-white">Booked Rooms</a>
                                {% endif %}
                            </div>
                            {% if user.is_authenticated %}
                                <a href="{% url 'users:ProfileView' %}" class="btn btn-dark text-primary" role="button"><i class="far fa-user"></i> Profile</a>
                                <a href="{% url 'account_logout' %}" class="btn btn-dark text-primary mx-auto" role="button"><i class="fa fa-sign-out-alt"></i> Log-out</a>
                            {% else %}
                                <a href="{% url 'account_login' %}" class="btn btn-dark text-primary mx-auto" role="button"><i class="fas fa-sign-in-alt"></i> Login</a>
                            {% endif %}
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- Header End -->
        {% block content %}
        {% endblock content %}

        
        <!-- Footer Start -->
        <footer class="container-fluid bg-dark text-light footer wow fadeIn mt-5" data-wow-delay="0.1s">
            <div class="container pb-5">
                <div class="row g-5">
                    <div class="col-md-6 col-lg-3">
                        <h5 class="section-title text-start text-accent text-uppercase mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Lekki, Lagos, Nigeria</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+2349010750893</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@hotelmiramarsg.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-12">
                        <div class="row gy-5 g-4">
                            <div class="col-md-6">
                                <h5 class="section-title text-start text-accent text-uppercase mb-4">Company</h5>
                                <a class="btn btn-link" href="{% url 'content_app:about' %}">About Us</a>
                                <a class="btn btn-link" href="{% url 'content_app:contact' %}">Contact Us</a>
                                <a class="btn btn-link" href="#">Privacy Policy</a>
                                <a class="btn btn-link" href="#">Terms & Condition</a>
                                <a class="btn btn-link" href="#">Support</a>
                            </div>
                            <div class="col-md-6">
                                <h5 class="section-title text-start text-accent text-uppercase mb-4">Services</h5>
                                <a class="btn btn-link" href="#">Accomodation</a>
                                <a class="btn btn-link" href="#">Dining Facilities</a>
                                <a class="btn btn-link" href="#">House Keeping</a>
                                <a class="btn btn-link" href="#">Concierge Services</a>
                                <a class="btn btn-link" href="#">GYM & Yoga</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="{% url 'content_app:home' %}">Hotel Miramar SG</a>, All Right Reserved.
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    </main>



    
    <!-- JavaScript libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" integrity="sha512-0QbL0ph8Tc8g5bLhfVzSqxe9GERORsKhIn1IrpxDAgUsbBGz/V7iSav2zzW325XGd1OMLdL4UiqRJj702IeqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/noframework.waypoints.min.js" integrity="sha512-fHXRw0CXruAoINU11+hgqYvY/PcsOWzmj0QmcSOtjlJcqITbPyypc8cYpidjPurWpCnlB8VKfRwx6PIpASCUkQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js" integrity="sha512-9CWGXFSJ+/X0LWzSRCZFsOPhSfm6jbnL+Mpqo0o8Ke2SYr8rCTqb4/wGm+9n13HtDE1NQpAEOrMecDZw4FXQGg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Templatejavascript -->
    <script src="{% static 'js/main.js' %}"></script>
    
</body>
</html>

templates/flash_messages.html
{% comment %} <!-- Flash Message Start --> {% endcomment %}
{% if messages %}
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
{% endif %}
{% comment %} <!-- Flash Message End --> {% endcomment %}

templates/rooms_list.html
{% load humanize %}


{% comment %} <!-- List all the room types available in the hotel --> {% endcomment %}
<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
    <div class="room-item shadow rounded overflow-hidden">
        <div class="position-relative">
            {% for room_image in room.roomimage_set.all|slice:":1" %}
            <img class="img-fluid" src="{{ room_image.image.url }}" alt="{{ room.room_type }}" style="height: 250px; width: 100%;">
            {% endfor %}
            {% for property in room.roomproperties_set.all %}
            <small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">{{ property.price_per_night|intcomma }} NGN/Night</small>
            {% endfor %}
        </div>
        <div class="p-4 mt-2">
            <div class="d-flex justify-content-between mb-3">
                <h5 class="mb-0">{{ room.room_type|capfirst }} Rooms</h5>
            </div>
            <div class="d-flex mb-3">
                {% for property in room.roomproperties_set.all %}
                <small class="border-end me-3 pe-3"><i class="fa fa-bed text-accent me-2"></i>{{ property.number_of_beds }} Bed(s)</small>
                <small class="border-end me-3 pe-3"><i class="fas fa-users text-accent me-2"></i>{{ property.capacity }} Person(s)</small>
                {% endfor %}
            </div>
            <p class="text-body mb-3">{{ room.description|truncatechars:100 }}</p>
            <div class="d-flex justify-content-between">
                <a class="btn btn-sm btn-primary rounded py-2 px-4" href="{{ room_url }}">View Detail</a>
            </div>
        </div>
    </div>
</div>